### ISSUE TITLE
Add number of pages to API endpoints

### ISSUE THREAD

**Issue by ksk5280** [LookingForMe/lookingfor#102]
Add the number of pages to the API endpoints so the front end can use this number as a reference for pagination. 

Here's an example for a way to set this up from http://jsonapi.org/examples/

{
  "meta": {
    "total-pages": 13
  },

> Note: Putting a property like "total-pages" in "meta" can be a convenient way to indicate to clients the total number of pages in a collection (as opposed to the "last" link, which simply gives the URI of the last page). However, all "meta" values are implementation-specific, so you can call this member whatever you like ("total", "count", etc.) or not use it at all.

**Comment by JaredRoth** [comment]
Closed by #107
