### ISSUE TITLE
Fix the workflow section of README to reflect cloning AND forking

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#106]
We should have a workflow for people who are cloning the repo (i.e. students on the team) and also have clear instructions for randos on the internet who will be forking the repo.

These instructions should be clear - and the cloning instructions should be top order so as not to be confusing.

Sufficient to just have the cloning instructions and a link to a github tutorial for forking.

**Comment by JaredRoth** [comment]
Personal note to also go over and clean/add other notes of interest. (Like error tracking channel)
