### ISSUE TITLE
Rails 5 Documentation

### ISSUE THREAD

**Issue by Salvi6God** [LookingForMe/lookingfor#110]
### Acceptance Criteria 
- Learn more about the new features Rails 5 provides and how it may be used on the backend
- Document on Basecamp my discoveries so other devs can learn as well

**Comment by Salvi6God** [comment]
Check basecamp!

**Comment by rrgayhart** [comment]
@Salvi6God - A link to the actual doc on basecamp would be helpful here - so folks interested in this won't be hunting around for it
