### ISSUE TITLE
Upgrade to a Concurrent Web Server 

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#14]
Size: 1

Acceptance Criteria:
- LookingFor is deployed on a concurrent web server

Resources:
- https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

**Comment by amcrawford** [comment]
Need to install puma to run Docker on Heroku; grabbing this issue as a part of my research spike.

**Comment by rrgayhart** [comment]
:+1:

**Comment by amcrawford** [comment]
Puma successfully installed and merged - closing issue.
