### ISSUE TITLE
Backround Worker to Run Job Fetcher(s)

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#17]
Size: 3

Right now we can run our job fetcher by typing `heroku run rake job_fetch:stackoverflow` - which is cool... but we're programmers and we should probably automate this.

Acceptance Criteria:
- One task runs all job fetch services
- That task is run every day at least once automatically

Resources:
https://devcenter.heroku.com/articles/scheduler

**Comment by slotaj** [comment]
@rrgayhart this should be good to go now that the scheduler is set up and we combined the two rake tasks into one

**Comment by rrgayhart** [comment]
:+1: :smile: :back: :construction_worker: 'er
