### ISSUE TITLE
Company Show

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#23]
As a user viewing a company show page, we should be able to see the company name, basic company information and a list of all jobs related to that company.

Acceptance Criteria:
- Company information should be shown
- All jobs related to company should be listed
  - jobs should be ordered by most recent
  - No more than 10 jobs should show automatically on the page (pagination)
- Company should have a list of technologies that have been tagged across all job postings.
- Link to company show is added to the index page for jobs

**Comment by dastinnette** [comment]
@rrgayhart pending your and @edgarduran's review, this should be good to go
