### ISSUE TITLE
AngelList API?

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#3]
Angellist has an API that may have jobs that we can use. We would like to have a scraper to pull in the job postings. 

Acceptance Criteria:
- Evaluate if Angel List is a viable service to scrape
- If it is...
  - Job Fetch Service pulls in jobs from Angel List Remote's RSS Feed
  - Service is tested
  - Service has an associated rake task to run it.
- If it isn't
  - Document why in the Basecamp for the project

Resources:
https://angel.co/api/spec/jobs

Concerns:
Many APIs rate limit usage. How do we make sure our application doesn't hit those rate limits?

**Comment by edgarduran** [comment]
It looks like it will not be possible to pull in the AngelList API for this app. Access to the API requires that an app be linked to a personal AngelList  account that  has "a verified email address and a Twitter, Facebook or LinkedIn account connected" to it. 

Also, per the terms of service they do not allow "Scraping and reposting job listings on your own job board."

I think it best to close this issue and find another source of job listing instead. 
@rrgayhart, let me know if you agree and we can close this issue.

**Comment by rrgayhart** [comment]
Excellent use of 'wontfix' label and this wraps up this issue in a well documented way. Thanks. Looks like it's time to close this one.
