### ISSUE TITLE
Port over New Relic to team owned account

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#49]
- Update basecamp
- Deploy Changes
- Confirm New Relic up and running

**Comment by slotaj** [comment]
@rrgayhart Are we still working on this part? I'd like to help if we could get this going so that we can start working on user and data loading testing.

**Comment by hhoopes** [comment]
Per conversation with @rrgayhart, we may or may not get the data we need from New Relic from the free plan. I'm going to create a new issue evaluating that vis a vis another option like Skylight, but currently New Relic IS running with a team account, so I believe this issue can be closed.
