### ISSUE TITLE
Normalization of Location

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#69]
Would be good to have this data normalize - Relates to #37

**Comment by rrgayhart** [comment]
Users should be able to query job postings by their location. ie if they are looking in North Carolina, they should be able to scope the job postings by this location.

Unsure how to implement this as location is not always accurate or uniform.

Fix could be beefing up uniformity of location on jobs OR some kind of elastic search across the contents of title and description OR kick off a background worker to do this string search and output a csv :fearful:

**Comment by rrgayhart** [comment]
^ Notes from closed issue. This story has needs clarification

**Comment by erinnachen** [comment]
It looks like all services we are currently using have an easy location tag to bind on... I think we can move location into its own table so that one can eventually find jobs by location.
