### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by ksk5280** [LookingForMe/lookingfor#73]
CORS - cross origin resource sharing.

We would like to hit the heroku API endpoint with our app, but we are unable to access it currently.

Chelsea set this up previously with a 'rack-cors' gem and David Whitaker just implemented this on his app, so they would be good resources.

**Comment by cheljoh** [comment]
See pinned snippet in boxtrot 1511 channel for an example of how I integrated the Rack Cors gem in one of my Rails project before- can't 100% guarantee it'll work in lookingfor app.

**Comment by erinnachen** [comment]
Cool, I'll pick this up and see what I can do.
