### ISSUE TITLE
API Jobs and Technologies Keys

### ISSUE THREAD

**Issue by cheljoh** [LookingForMe/lookingfor#76]
Would like to have the ids for each job and technology returned in the JSON response. Right now, the endpoint returns only the company id.  Would like something like this:

![image](https://cloud.githubusercontent.com/assets/14203424/15787306/d2c3ebca-297e-11e6-9d0e-ecebfc5af30c.png)

^That is the fake data we are using right now. Thanks!

**Comment by ksk5280** [comment]
FYI, the sample jobs code above is located here: https://github.com/LookingForMe/lookingForFrontEnd/blob/master/lib/sample-jobs.js
