### ISSUE TITLE
Capitalization for Technologies

### ISSUE THREAD

**Issue by cheljoh** [LookingForMe/lookingfor#82]
Technologies returned with a Job object in the Job index API endpoint are all lowercase: 
`"technologies": [
{
"id": 1,
"name": "ruby"
},
{
"id": 2,
"name": "javascript"
}
]`

Would be great to render these with proper capitalization- we can also work on in front-end if needed. Thanks!

**Comment by erinnachen** [comment]
@cheljoh They are stored in the database without capitalization. Maybe @hhoopes or @brennanholtzclaw can take a look at serializing them.

**Comment by hhoopes** [comment]
Yep, @cheljoh and I discussed this and she said she'd create an issue for it and I'll be taking the issue.
