### ISSUE TITLE
Endpoints for Technologies

### ISSUE THREAD

**Issue by brianrip** [LookingForMe/lookingfor#92]
@hhoopes @erinnachen @NickyBobby 
Serve endpoints for jobs by each technology:
Ruby
Rails
Javascript
React
Go
Ember
Clojure
Angular
Python

**Comment by hhoopes** [comment]
Apologies for being pedantic, but I'm guessing you don't want a specific endpoint for each, but would like to iterate through them. so basically a technology show endpoint with all the associated jobs?

**Comment by brianrip** [comment]
We were thinking an endpoint scoped to each particular technology. So one that serves ruby.jobs and so forth.
